version: '3'
services:
  db:
    image: postgres:11
    container_name: billboard-map
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
